# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: 'sonergezgen/docker-react-app:$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: 'Default'
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: "10.x"
      displayName: Install Node.js

    - script: npm install
      displayName: "Install NPM"    

    - script: npm test -- --watchAll=false
      displayName: "Test"

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile.dev'
        tags: |
          $(tag)