# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  - name: tag
    value: sonergezgen/docker-react-app:$(Build.BuildId).dev

stages:
- stage: Build
  displayName: Build image and Run Tests
  jobs:
  - job: Build
    displayName: Build
    pool:
     name: 'Default'
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: "10.x"
      displayName: Install Node.js

    - script: npm install
      displayName: "Install NPM"

    - script: npm test -- --watchAll=false
      displayName: Run all tests

    - task: Docker@2
      displayName: Build the Image and push
      inputs:
        containerRegistry: 'dockerHub'
        repository: 'sonergezgen/reactapp'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.dev'
        tags: '$(tag)'

