FROM node:14.20.1-alpine3.15

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"] #Starts a DEV server locally. NOT for production envoirement purposes.